### ISSUE TITLE
How to highlight an asymmetrical interval?

### ISSUE THREAD

**Issue by arthur-albuquerque** [mjskay/ggdist#105]
Hi Matthew, 

I was looking into [ggdist's documentation](https://mjskay.github.io/ggdist/articles/slabinterval.html), more specifically the "Highlighting and other combinations" topic. I want to do that, but with an asymmetrical interval, let's say between 1/1.1 and 1.1. 

Is it possible with ggdist? I couldn't find any compatible code.

Best,

Arthur

**Comment by mjskay** [comment]
Ah I see! 

`1/1.1 < x` is `TRUE` when `1/1.1` is less than `x`, which is equivalent to writing `x > 1/1.1`, i.e. it will be `TRUE` when x is larger than 1/1.1. If you AND that (the `&` operator) with `x < 1.1`, which will be `TRUE` when x is less than 1.1, you have a condition that is `TRUE` when x is between `1/1.1` and `1.1` and `FALSE` otherwise. 

In other words, you could write `1/1.1 < x & x < 1.1` as `x > 1/1.1 & x < 1.1`, both statements are equivalent and get you the desired outcome. I prefer the first way because it is closer to how we'd typically write such intervals in mathematical shorthand, i.e. 1/1.1 < *x* < 1.1, which is not valid R syntax.
