### ISSUE TITLE
Dot plot with `aes(color = )` and `position_dodge()`?

### ISSUE THREAD

**Issue by SchmidtPaul** [mjskay/ggdist#122]
Hi and thanks for the great package!
I took inspiration from [this blogpost](https://solomonkurz.netlify.app/post/2021-09-22-sexy-up-your-logistic-regression-model-with-logit-dotplots/#:~:text=stat_dots(data%20%3D%20bechdel%20%25%3E%25%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20mutate(binary%20%3D%20factor(binary%2C%20levels%20%3D%20c(%22PASS%22%2C%20%22FAIL%22)))%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20aes(y%20%3D%20pass%2C%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20side%20%3D%20ifelse(pass%20%3D%3D%200%2C%20%22top%22%2C%20%22bottom%22)%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20color%20%3D%20binary)%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20scale%20%3D%200.4%2C%20shape%20%3D%2019)) and was able to create a similar plot:

``` r
library(ggdist)
library(tidyverse)

dat <- tibble::tribble(
  ~pass, ~year, ~grp,
     1L, 2020L,    "A",
     1L, 2021L,    "A",
     1L, 2022L,    "A",
     0L, 2020L,    "A",
     1L, 2021L,    "A",
     0L, 2022L,    "A",
     0L, 2020L,    "B",
     0L, 2021L,    "B",
     0L, 2022L,    "B",
     0L, 2020L,    "B",
     0L, 2021L,    "B",
     1L, 2022L,    "B"
  ) %>% 
  mutate_if(is.character, as.factor)

ggplot() +
  stat_dots(
    data = dat,
    aes(
      x = year,
      y = pass,
      side = ifelse(pass == 0, "top", "bottom")
    ),
    position = "identity",
    orientation = "horizontal",
    shape = 19,
    scale = 0.1
  )
```

![](https://i.imgur.com/vlUQRPP.png)

<sup>Created on 2022-01-12 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

However, I then tried adding `color = grp` and get an unexpected outcome: some dots are missing. 

``` r
ggplot() +
  geom_dots(
    data = dat,
    aes(
      x = year,
      y = pass,
      side = ifelse(pass == 0, "top", "bottom"),
      color = grp
    ),
    position = "identity", # dodge?!
    orientation = "horizontal",
    shape = 19,
    scale = 0.1
  )
```

![](https://i.imgur.com/ebcw1R3.png)

<sup>Created on 2022-01-12 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Also, even if it did show all dots, I thought about using something like `position = "dodge"` in order to get the dots per year and side arranged like shown below. Is this possible?
![image](https://user-images.githubusercontent.com/31928213/149138437-dc5aadb4-3859-469d-9c92-6d0f6422cba7.png)

**Comment by mjskay** [comment]
Good questions.

Re: dots disappearing: they are drawn, but overlapping. If you add alpha values (and a mapping onto shape) you can see how they overlap more easily:

```r
ggplot() +
  geom_dots(
    data = dat,
    aes(
      x = year,
      y = pass,
      side = ifelse(pass == 0, "top", "bottom"),
      color = grp,
      shape = grp
    ),
    position = "identity", # dodge?!
    orientation = "horizontal",
    # shape = 19,
    scale = 0.1,
    alpha = 0.5
  )
```
![image](https://user-images.githubusercontent.com/6345019/149206063-0f2cb7c6-2213-4bf5-a130-926e2ec1c582.png)

If you set `group` to `NA` they will be stacked together instead (this overrides the fact that setting `color` to a discrete variable automatically sets `group` to group by that variable as well):

```r
ggplot() +
  geom_dots(
    data = dat,
    aes(
      x = year,
      y = pass,
      side = ifelse(pass == 0, "top", "bottom"),
      color = grp,
      group = NA
    ),
    position = "identity", # dodge?!
    orientation = "horizontal",
    shape = 19,
    scale = 0.1
  )
```
![image](https://user-images.githubusercontent.com/6345019/149206251-2e6f253b-7120-4076-a2b3-ca3a7fbb0349.png)


This doesn't quite do what you're looking for though with your second question. Unfortunately `position = "dodge"` won't either, as it is designed for dodging perpendicular to the orientation of the geometry rather than applying as offset along the same axis.

In your case, with discrete data, you could hack together a rough version of what you want by manually adding values to the x variable conditional on the group. This will be brittle in that it will be sensitive to the size and aspect ratio of the chart (which influences the algorithm that determines the size of the dots), but if you have fixed data and chart parameters it shouldn't be too hard to pick a reasonable offset. For example, something like this:

```r
ggplot() +
  geom_dots(
    data = dat,
    aes(
      x = year + 0.1 * (grp == "A"),
      y = pass,
      side = ifelse(pass == 0, "top", "bottom"),
      color = grp
    ),
    position = "identity", # dodge?!
    orientation = "horizontal",
    shape = 19,
    scale = 0.1
  )
```
![image](https://user-images.githubusercontent.com/6345019/149206767-1551a53a-433a-4ba7-82e7-0f53d1b91e07.png)

Sadly not as elegant as I'd like, but hopefully gets the job done?

**Comment by SchmidtPaul** [comment]
Good enough, thanks a lot!
