### ISSUE TITLE
Allow missing `y` aesthetic in `geom_lineribbon()`

### ISSUE THREAD

**Issue by Bisaloo** [mjskay/ggdist#127]
There are cases where the input data is missing a central tendency (be it mean, median, etc.).

Yet, `geom_lineribbon()` makes the `y` mandatory and if it's filled with `NA` values, the entire row is dropped and no ribbon is displayed.

It would be good in these cases if ribbons could be displayed without the line. `geom_ribbon()` doesn't work well either in these cases because:

1. I want to use this inside a function and there will be case when the central tendency is present and cases when it's absent
2. Even when the central tendency is missing, there might be multiple quantiles and thus a need for multiple overlapped ribbons.

Opened as part of https://github.com/epiforecasts/scoringutils/issues/174.

**Comment by mjskay** [comment]
Hmmm makes sense, seems a good use case to support.

In the short term, a workaround that works with the CRAN version of {ggdist} is to set `y` to a constant non-`NA` value but suppress the line by setting `color` or `size` to `NA`. Something like:

```r
data.frame(x = 1:10, y = 1:10) %>%
  ggplot(aes(x = x, ymin = y - 1, ymax = y + 1)) +
  geom_lineribbon(y = 0, color = NA)
```
![image](https://user-images.githubusercontent.com/6345019/152282585-8c124234-dfd4-492e-8dde-f9bf6a73511b.png)

A better long-term solution I can see is that if I make the off-axis positional aesthetic non-required `geom_lineribbon()` will work as-is and the line won't be drawn if you omit the `y` mapping. If you install the `dev` branch (`devtools::install_github("mjskay/ggdist@dev")`) I just implemented that solution; in which case something like this should work:

```r
data.frame(x = 1:10, y = 1:10) %>%
    ggplot(aes(x = x, ymin = y - 1, ymax = y + 1)) +
    geom_lineribbon()
```
![image](https://user-images.githubusercontent.com/6345019/152282585-8c124234-dfd4-492e-8dde-f9bf6a73511b.png)

Let me know if that works for what you need. Hopefully this version should be on CRAN soon since I am in the midst of preparing a release anyway.

**Comment by Bisaloo** [comment]
Thanks for your quick answer and changes. This is very helpful!
