### ISSUE TITLE
Add "missing" bare slab stats

### ISSUE THREAD

**Issue by bwiernik** [mjskay/ggdist#135]
Most of the slab stats (slab, dots, etc.) have both bare and +interval versions. 4 don't (hist, gradient, cdf, ccdf). Do you think it would be possible to add versions of these 4 without the point and interval included? This would be useful to be able to control the positioning of each part separately. The main one I'm currently interested in hist.

**Comment by mjskay** [comment]
Hmmm I've been trying to limit some of the shortcuts since (in theory) they can all be recreated from `stat_slabinterval()` or `geom_slabinterval()`. The documentation now attempts to make this clearer with auto-generated code chunks at the top of each geom/stat page giving the options used to create the corresponding shortcut geom, under "Roughly equivalent to:".

e.g. if you look at the options used to create `stat_slab()` at the top of its [doc page](https://mjskay.github.io/ggdist/reference/stat_slab.html) probably the simplest way to get rid of the intervals with the stat forms is something like `stat_histinterval(geom = "slab")`. You could also do something like `stat_histinterval(color = NA)`, or go the other way and start from `stat_slab()` and pass it the options used to create the histogram listed at the top of the [stat_histinterval() doc page](https://mjskay.github.io/ggdist/reference/stat_histinterval.html), which might be something like `stat_slab(slab_type = "histogram")`.

That said, I'm not necessarily opposed to creating these shortcuts, I just want to be cautious about creating infrequently-used ones. The idea behind the shortcuts was mostly to cover frequently-used combinations that might be hard to remember. Maybe it would help me to understand what your use case is for them?

**Comment by bwiernik** [comment]
The main one I'm interested in is hist. I'm coming to prefer histograms over densities at least in some situations. I usually like to dodge the intervals a bit separately from the slab (like in the vignette example), so being able to do that easily with hist would be really useful for me

**Comment by mjskay** [comment]
Ah k cool! Yeah, there are really only three geoms/stats in ggdist: lineribbon, slabinterval, and dotsinterval. Everything else is just shortcuts for options that can be recombined as you want.
