### ISSUE TITLE
Legend customization 

### ISSUE THREAD

**Issue by Dallak** [mjskay/ggdist#145]
Hi,

Is there a way to customize the legend and remove the black horizontal line that comes with `fill = stat(abs(x) < 0.1))`? Circled in red. It seems a bit distracting but I am sure that there is some way to fix it that I have not figured it out yet. 

Also, it is possible to capitalize the label `level` so it looks similar to `Rope`?

![Rplot05](https://user-images.githubusercontent.com/47871346/184523270-f1b7d397-4ea4-49fa-b6f1-a1c1a507cec7.png)

Many thanks in advance!

**Comment by mjskay** [comment]
Ah yeah --- because you are setting `size = 2` on the call to `stat_interval()`, then the legend for `fill` has `size = 2` applied to it, which means it gets a sub-geometry for the interval, which is the black line you are seeing. You can override aesthetics for a specific legend using the `override.aes` argument to `guide_legend()`. In your case, this means adding something like:

`guide = guide_legend(override.aes = list(interval_size = NA))`

to the call to your fill scale function (in this case `scale_fill_manual()`) so that the size of the interval is set to `NA` for the legend and the black line is not drawn.

Re: the title of "level", this is just an automatic `color` scale, so you can change it the same way you change other scale titles, e.g. by passing `color = "Level"` to the `labs()` function.

An example with both changes:

```r
data.frame(x = rnorm(1000), var = c("a","b")) %>% 
  ggplot(aes(x, var, fill = stat(abs(x) < 1.5))) + 
  stat_halfeye(scale = 0.5) +
  stat_interval(position = position_nudge(y = -0.2), size = 2)+
  scale_fill_manual(values = c("gray80", "skyblue"), guide = guide_legend(override.aes = list(interval_size = NA))) +
  scale_color_brewer() +
  labs(
    fill = "Rope",
    color = "Level"
  )
```
![image](https://user-images.githubusercontent.com/6345019/184558169-96232b1f-d796-46d5-9fcd-848de6424de4.png)
