### ISSUE TITLE
Help with stacking dots with categorical variables

### ISSUE THREAD

**Issue by ShacharHochman** [mjskay/ggdist#153]
Hi, and thank you for developing this fantastic package.

I am trying to add stacked dots to the margins of a plot, but it doesn't really work for me. 

```{r}
library(stats)
library(emmeans)
library(tidyverse)
library(ggdist)

set.seed(123)
DF <- data.frame(Y = rbinom(50,1,0.3),
                 Var1 = sample(size = 50,c("A","B"),replace = T),
                 Var2 = sample(size = 50,c("C","D"),replace = T))

Model <- glm(data = DF, Y~Var1*Var2,family = binomial)

Data4Plot <- emmeans(Model,~Var1*Var2, type = "response") %>% as.data.frame()


ggplot(Data4Plot, aes(x = Var1, colour = Var2, y = prob))+
  geom_errorbar(aes(ymax = asymp.UCL, ymin = asymp.LCL),
                position = position_dodge(0.3),width = 0.2) +
  geom_point(size = 1.5,position = position_dodge(0.3))+
  stat_dots(data = DF,layout = "bin",
            aes(y = Y,
                side = ifelse(Y == 0, "top", "bottom"),
                color = Var2,
                x = Var1),     
            side = "bottomright",
            position = position_dodge(0.3))

```

What I am getting is this:

![PlotGit](https://user-images.githubusercontent.com/58937060/194704258-600284f6-05dc-45d5-8a38-484dbe73a79f.jpg)

I hoped the dots would be stacked under each line or at least won't overlap like this. 

I'd appreciate any tips and insights.

**Comment by mjskay** [comment]
Yeah, this one's a bit tricky.

I'm not 100% sure what you're looking for, so here are two things that might be close. The first one is simpler: if you want the stacks running horizontally but not overlapping, I would pick the side based on `Var1`; something like this:

```r
ggplot(Data4Plot, aes(x = Var1, colour = Var2, y = prob))+
  geom_errorbar(aes(ymax = asymp.UCL, ymin = asymp.LCL),
                position = position_dodge(0.3),width = 0.2) +
  geom_point(size = 1.5,position = position_dodge(0.3))+
  geom_dots(data = DF,layout = "bin",
            aes(y = Y,
                side = ifelse(Var2 == "C", "left", "right"),
                color = Var2,
                x = Var1),
            shape = 19,
            scale = 0.5
    )
```
![image](https://user-images.githubusercontent.com/6345019/194722318-ec0022dc-2389-4380-9ead-c89b2aa59598.png)

If you want them vertical, it's a bit trickier. You have to override the orientation detection and change the geom orientation to `"horizontal"` (horizontal here meaning the direction of the base of the dots, thus "horizontal" instead of "vertical"). Unfortunately you can't use `position_dodge` here because it will dodge in the opposite direction of what you want, so we have to manually calculate the dodge by adjusting the `x` aesthetic mapping. It gets pretty ugly:

```r
library(stats)
library(emmeans)
library(tidyverse)
library(ggdist)

set.seed(123)
DF <- data.frame(Y = rbinom(50,1,0.3),
                 Var1 = sample(size = 50,c("A","B"),replace = T),
                 Var2 = sample(size = 50,c("C","D"),replace = T))

Model <- glm(data = DF, Y~Var1*Var2,family = binomial)

Data4Plot <- emmeans(Model,~Var1*Var2, type = "response") %>% as.data.frame()


ggplot(Data4Plot, aes(x = Var1, colour = Var2, y = prob))+
  geom_errorbar(aes(ymax = asymp.UCL, ymin = asymp.LCL),
                position = position_dodge(0.3),width = 0.2) +
  geom_point(size = 1.5,position = position_dodge(0.3))+
  geom_dots(data = DF,layout = "bin",
            aes(y = Y,
                side = ifelse(Y == 0, "top", "bottom"),
                color = Var2,
                x = as.numeric(factor(Var1)) + (Var2 == "D") * 0.3 - 0.15),
            shape = 19,
            scale = 0.2,
            orientation = "horizontal"
    )
```
![image](https://user-images.githubusercontent.com/6345019/194722446-5140a468-0c7a-4fa6-9730-ee6c15ed3d49.png)

**Comment by ShacharHochman** [comment]
Dear Matthew,

Thank you so much for helping me with it. 

I hoped that where there are quite a few dots (e.g., the bottom side), there would be a pile of dots rather than a line of them (or at the very least that they won’t overlap, but this you solved!).

Maybe giving the dots random values that fit the y-axis would make it work?

Thanks again,

Shachar

**Comment by mjskay** [comment]
> I hoped that where there are quite a few dots (e.g., the bottom side), there would be a pile of dots rather than a line of them (or at the very least that they won’t overlap, but this you solved!).

If I understand what you're asking, currently something like that does require manually adding offsets to create the pile (randomly, as you suggest, or perhaps via an evenly-spaced grid). In the future, I do plan to support something like this; see #100. For now, I'll close this issue since there's a workaround and future support will happen via that other issue. Thanks!
