### ISSUE TITLE
More layouts for geom_dots*() (especially for large n)

### ISSUE THREAD

**Issue by mvuorre** [mjskay/ggdist#161]
It would be nice to have more alternatives for the `layout` argument in `geom_dots()` and friends, as discussed [here](https://fediscience.org/@mjskay/109467481228076107).

Specifically, I have in mind the quasi- and pseudorandom positions in the [vipor](https://github.com/sherrillmix/vipor) package, some of which are available easily in ggplot2 through the [ggbeeswarm](https://github.com/eclarke/ggbeeswarm) package (especially the `position_quasirandom()` layouts). Moreover, since ggdist already offers nice one-sided versions of slabs, it would be *awesome* to have e.g. a one-sided quasirandom layout, so you could plot groups next to another for easy visual comparison.

I explored some of these alternatives [here](https://vuorre.netlify.app/posts/raincloud-plot-alt/), but rather unsuccesfully. 

Kudos for the awesome pkg btw. I use it all the time!

**Comment by mjskay** [comment]
Thanks! 

Yeah, I can see an argument for this kind of thing for when regular layouts don't scale. Another layout designed to address scaling issues is Daniel Zvinca's [density dotplots](https://www.linkedin.com/pulse/pursuit-diversity-data-visualization-jittering-access-daniel-zvinca/), so I might want to have something like that too.

**Comment by mvuorre** [comment]
Yeah, that's great, this is basically what I had in mind (fig 23 in the blog post):

![](https://media-exp1.licdn.com/dms/image/C5612AQFyJQDFLFu-oQ/article-inline_image-shrink_1500_2232/0/1530887300430?e=1675900800&v=beta&t=9wr80JsTQ1Ke1Wp1FgaJ6z4YXtRZSzMM2JAd8CyvR_4)

But with all the ggdist goodies 💎

**Comment by mjskay** [comment]
Dunno how Daniel Zvinca made those density dotplots, but I came up with one quick and dirty way that doesn't even seem to need a new layout algorithm. e.g.:

```r
set.seed(1234)
x = rnorm(1000)

ggplot() +
  geom_dots(aes(x))
```
![image](https://user-images.githubusercontent.com/6345019/206068757-653a6f6e-4c1a-42af-b5a4-3a410fb50aac.png)

Now, a quick-and-dirty approach to density smoothing:

```r
# smooth x using a density estimator, returning new x of the same length
# (N.B. order is destroyed here, so output points have no correspondence
# to input points... might have to think about that)
smooth = function(x) {
  d = density(x)
  n = length(x)
  
  # determine how many (fractional) dots in each bin of the density estimate's grid
  bin = d$x
  f_times_n = d$y / sum(d$y) * n
  
  # get whole number counts of dots in each bin (guaranteeing they add up to
  # exactly n) by rounding the CDF implied by the density estimate
  F_times_n = round(cumsum(f_times_n))
  n_in_bin = F_times_n - c(0, F_times_n[-length(F_times_n)])
  
  # turn bins and counts into n values we can plot 
  inverse.rle(list(lengths = n_in_bin, values = bin))
}

ggplot() +
  geom_dots(aes(x = smooth(x)))
```
![image](https://user-images.githubusercontent.com/6345019/206068926-a7616b80-eb06-466e-8d9d-9672e8a3e0ba.png)

Still some details to work out (like, where to put this in the API --- not sure if it counts as a layout algorithm or something else....) but at first look seems easy enough to do!

**Comment by mvuorre** [comment]
1. Amazing work.
2. Looks like #113 solves this too so that makes sense.

Thanks and keep up the good work!

**Comment by mjskay** [comment]
okay I had to figure out how to do weighted quantile estimation to actually do this properly, but an initial version is now on the [weighted-quantiles](https://github.com/mjskay/ggdist/tree/weighted-quantiles) branch if you want to try it out. For now I'm keeping it as a transformation function to be applied to the data rather than an option to `geom_dots()`. So you can do:

```r
set.seed(1234)
x = rnorm(1000)

ggplot() +
  geom_dots(aes(x = smooth_dots(x)))
```
![image](https://user-images.githubusercontent.com/6345019/206949189-16e01915-1c4c-453f-bbd7-a389a962265e.png)

While looking at other examples of this I saw it was sometimes paired with a hex-packing layout and I thought it looked pretty nice, so I added that too:

```r
ggplot() +
  geom_dots(aes(x = smooth_dots(x)), layout = "hex", stackratio = 0.9)
```
![image](https://user-images.githubusercontent.com/6345019/206949305-649578bb-b8a7-43ec-8a8e-d50992f7e672.png)

Of course this stuff also works with all the other options, e.g. changing side:

```r
ggplot() +
  geom_dots(aes(x = smooth_dots(x)), layout = "hex", stackratio = 0.9, side = "both")
```
![image](https://user-images.githubusercontent.com/6345019/206949495-37b63f8b-0363-41be-a827-1d76cfe2f936.png)

One question for you, @mvuorre: do you still have a need for a quasi-random layout? I'd love to know if these new options satisfy the use cases you were thinking about, or if you have use cases where a quasi-random layout would still be helpful to have.

**Comment by mjskay** [comment]
Ah hrm, this wont be a good long-term solution since the smoothing should be applied to each group separately. Blast! I'll have to make it an argument or something then. Oh well.

**Comment by mvuorre** [comment]
Thanks so much for the effort on this. I am not quite sure if this will work for what I had in mind, I've tried some smaller sample distributions with many peaks and cannot get it to display well. For example:

```r
library(ggplot2)
library(ggdist)
set.seed(1234)
x = c(rnorm(50), rnorm(50, 3))

ggplot() +
  geom_dots(aes(x = smooth_dots(x)), binwidth = .05, dotsize = 1)
```

![image](https://user-images.githubusercontent.com/7349270/207008642-1eb6a5d9-b706-4e87-99fc-56191a09f332.png)

**Comment by mjskay** [comment]
You've manually picked a very small bin size --- if you let it pick the binwidth automatically, are there problems with the result?

Unsmoothed:

```r
set.seed(1234)
x = c(rnorm(50), rnorm(50, 3))

ggplot() + 
  geom_dots(aes(x = x), dotsize = 1)
```
![image](https://user-images.githubusercontent.com/6345019/207179449-8511b8f5-db9a-4264-82c3-694b126b923f.png)

Smoothed:

```r
ggplot() + 
  geom_dots(aes(x = smooth_dots(x)), dotsize = 1)
```
![image](https://user-images.githubusercontent.com/6345019/207179724-ff56fc70-31cd-4d25-b47a-04b598c4f289.png)

Personally I'd go with unsmoothed here b/c of the small sample size, but either way I don't think I'd prefer a quasirandom layout over the dotplot layout. But I may not have found the right example of them yet. Possibly if there's a large, constant spike? Though even then I'd maybe adjust stackratio to be < 1 and/or dotsize to be > 1 rather than use a quasirandom layout (which should also be automatable using #162).

**Comment by mvuorre** [comment]
I see, thanks that makes sense. I don't think there are problems with the output that way. At this point I think it is just a matter of style/taste. I'm not expecting you to take `geom_dots()` in this direction but here's just my 2 cents and what I'm trying to do: Possibly many comparisons of two groups (e.g. male/female) shown with "mirrored" dotplots/jittered points etc. If I draw this with the current `geom_dots(smooth_dots(...))` (and my limited skill in using it), I get a plot that basically (to my eye) bins the points too hard for me to "see" the comparisons.

``` r
library(tidyverse)
library(ggdist)
library(ggbeeswarm)
set.seed(1234)

dat <- tibble(
  f1 = rep(1:4, each = 50), 
  f2 = rep(1:2, length = 200),
  y = rnorm(200, f1 + f2 * .25)
) %>% 
  mutate(across(f1:f2, factor))


dat %>% 
  ggplot() + 
  geom_dots(
    aes(
      x = f1, 
      y = y, 
      fill = f2, 
      side = if_else(f2=="1", "left", "right")
    )
  )
```

![](https://i.imgur.com/y76EJH2.png)

I get very close to my desired results with `position_quasirandom()`, but the points are jittered both left and right. I'd like the points on the left to only be jittered left, and points on the right to only be jittered to the right.

``` r

dat %>% 
  ggplot() +
  aes(x = f1, y = y, col = f2) +
  geom_point(
    position = position_quasirandom(width = .25/4, dodge.width = .25)
  )
```

![](https://i.imgur.com/NzPDlBt.png)

Maybe there is a way to specify that with `geom_dots() / smooth_dots()`? Another closely related method of jittering is in [`geom_sina()`](https://ggforce.data-imaginist.com/reference/geom_sina.html), but that is also two-sided.

Anyway these were just my ramblings. Feel free to ignore as a special use case and not general enough to warrant changes in how you see ggdist & `geom_dots()` working. Keep up the good work and thank you!

<sup>Created on 2022-12-13 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by mjskay** [comment]
Ah got it! This is very helpful, thanks!

I think my main issue with `quasirandom` / `sina` is my bias towards layouts that are a bit more intentional --- it feels like there should be a better solution to the problems they solve. Thus, I really appreciate you giving me more info on your use case, which is exactly what I need to figure out something that might (hopefully) satisfy both of us :). Plus, I don't really know how I would do automatic binning with `sina`, since the height of a bin is not constrained by its width...

My first thought from the example you gave is that if you want smaller dots, there are two things to try: (1) reduce `scale` so that the dotplot takes up less space or (2) pass an interval to `binwidth` to set a maximum bin width.

(I'll give these examples using the `dev` branch, which has some improvements to dot layout)

E.g. a similar plot to your `position_quasirandom` example might use `scale = 0.25` to make `geom_dots()` find a binwidth such that the dotplots take up at most `0.25` of their allotted space (I also set `linewidth = 0` to get rid of dot outlines):

```r
library(tidyverse)
library(ggdist)
set.seed(1234)

dat <- tibble(
  f1 = rep(1:4, each = 50), 
  f2 = rep(1:2, length = 200),
  y = rnorm(200, f1 + f2 * .25)
) %>% 
  mutate(across(f1:f2, factor))


dat %>% 
  ggplot() + 
  geom_dots(
    aes(
      x = f1, 
      y = y, 
      fill = f2, 
      side = if_else(f2=="1", "left", "right")
    ),
    scale = 0.25,
    linewidth = 0
  )
```
![image](https://user-images.githubusercontent.com/6345019/208572965-a990895b-7e87-47db-8af9-0573f10363d2.png)

Alternatively, you might decide you want the bin width in the y dimension to be at most 0.1, if that is some domain-relevant resolution at which you want to be able to see dots. If you set `binwidth = c(0, 0.1)`, the automatic binwidth algorithm will find a width in that range:

```r
dat %>% 
  ggplot() + 
  geom_dots(
    aes(
      x = f1, 
      y = y, 
      fill = f2, 
      side = if_else(f2=="1", "left", "right")
    ),
    binwidth = c(0, 0.1),
    linewidth = 0
  )
```
![image](https://user-images.githubusercontent.com/6345019/208573469-61c4a33b-765e-41e9-8fa8-1ddb6715e552.png)

The other thing I'm getting from your example is that maybe you want the dots to be in their exact `y` positions. There are two combinations of options in ggdist that guarantee this: `layout = "swarm"`, or `layout = "weave", nudge_overlaps = FALSE` (the `nudge_overlaps` option is only in the dev version and is likely to change its name before release). E.g.:

```r
dat %>% 
  ggplot() + 
  geom_dots(
    aes(
      x = f1, 
      y = y, 
      fill = f2, 
      side = if_else(f2=="1", "left", "right")
    ),
    binwidth = c(0, 0.1),
    linewidth = 0,
    layout = "swarm"
  )
```
![image](https://user-images.githubusercontent.com/6345019/208573989-79cd58c7-f5d1-49e1-9b9b-ae693d271df3.png)

At this point, if you find the dots too small and want them to be visually bigger while maintaining the bin width of 0.1 (and exact y positions), you could also pick some number `k > 1` and set `dotsize = k` (visual width of the dot relative to bin size) and `stackratio = 1/k` (stacking height between dots). E.g.:

```r
dat %>% 
  ggplot() + 
  geom_dots(
    aes(
      x = f1, 
      y = y, 
      fill = f2, 
      side = if_else(f2=="1", "left", "right")
    ),
    binwidth = c(0, 0.1),
    linewidth = 0,
    layout = "swarm",
    dotsize = 1.5,
    stackratio = 1/1.5
  )
```
![image](https://user-images.githubusercontent.com/6345019/208575493-d7323822-c438-4933-8596-9f52b2bad447.png)

Is this closer to what you're looking for?

This also makes me think that if you want an exact binwidth (say `0.1`) and just want the algorithm to pick a `dotsize` and `stackratio` to make the layout with that binwidth *and* visual dot size fit in the available space, that could be helpful. I opened an issue for that at #162.

**Comment by mjskay** [comment]
I've now implemented a solution in #162 that automatically tweaks dotsize and stackratio, which I think lets you get a solution in line with what you're looking for. e.g.:

```r
dat %>% 
  ggplot() + 
  geom_dots(
    aes(
      x = f1, 
      y = y, 
      fill = f2, 
      side = if_else(f2=="1", "left", "right")
    ),
    linewidth = 0, 
    scale = 0.25,
    binwidth = unit(5, "pt"),
    layout = "swarm",   # or layout = "weave", overlaps = "keep"
    overflow = "compress"
  )
```
![image](https://user-images.githubusercontent.com/6345019/209606278-962bdf16-ddf4-4b24-9c5a-a504f4660e13.png)

This says:

- ensure each dotplot fits into 25% of the allotted space for the geom (`scale = 0.25`)
- make the bins/dots be 5 points in size (`unit(5, "pt"`)
- use a layout where y positions of dots are exact (`layout = "swarm"` or `layout = "weave", overlaps = "keep"`)
- if the above `binwidth` setting would cause the dotplot to go beyond the requested 25% of the geom space (per `scale`), compress the distances between dots so that the dot sizes stay at 5 points but the dots may overlap a bit (`overflow = "compress"`)

I might consider making a shortcut geom like a `geom_swarm()` and/or `geom_weave()` with this combo of binwidth/layout/overflow settings (then the only thing you'd need to set is `scale` if doing multiple together with dodging). Might be useful for EDA type applications.

**Comment by mjskay** [comment]
I made the shortcut versions of these (`geom_swarm()` and `geom_weave()`), defaulting to `side = "both"` and `overflow = "compress"`, with `binwidth = unit(1.5, "mm")`, which is the same dot size as `geom_point()`. e.g.:

```r
library(dplyr)
library(ggplot2)
library(ggdist)

set.seed(1234)
data.frame(
    x = rnorm(400, c(1,4)),
    g = c("a","b")
) %>%
    ggplot(aes(x, y = g, fill = g)) +
    geom_weave(linewidth = 0)
```
![image](https://user-images.githubusercontent.com/6345019/211236692-78203281-0cfa-49b8-8331-b2cb0b3cae86.png)

I also added a `scale_side_mirrored()` to make setting the `side` aesthetic more grammar-of-graphics-like (#142). e.g.:

```r
set.seed(1234)
data.frame(
    x = rnorm(400, c(1,4)),
    g = c("a","b")
) %>%
    ggplot(aes(x, fill = g, side = g)) +
    geom_weave(linewidth = 0, scale = 0.5) +
    scale_side_mirrored()
```
![image](https://user-images.githubusercontent.com/6345019/211236985-6a0c2523-471c-4ad2-821d-1dda72692216.png)


I think that should cover all the use cases in this issue, so I am closing it for now. However, please let me know if there's something that doesn't work as expected / is not covered by this! Thanks again for the feedback.

**Comment by mvuorre** [comment]
Hi! This is really amazing, and I think it works well with what I'm doing. Now onto writing the manuscripts 😉. Thank you for the detailed examples as well!

**Comment by mjskay** [comment]
You're welcome! Good luck on the manuscripts!
