### ISSUE TITLE
Binned rvar slabs with integers

### ISSUE THREAD

**Issue by mattansb** [mjskay/ggdist#177]
Note sure what's going on here... Which of the following is the bug?

``` r
library(ggplot2)
#> Warning: package 'ggplot2' was built under R version 4.2.3
library(ggdist)

x <- rpois(4000, lambda = 30)
class(x)
#> [1] "integer"

ggplot() + 
  stat_slab(aes(x = x))
```

![](https://i.imgur.com/zW6KtIE.png)

But with an ravr…

``` r
xrvar <- posterior::rvar(x)
ggplot() + 
  stat_slab(aes(xdist = xrvar))
```

![](https://i.imgur.com/KRfo501.png)

``` r

ggplot() + 
  stat_slab(aes(xdist = xrvar + 0)) # coerce to double
```

![](https://i.imgur.com/bSrL3Af.png)

<sup>Created on 2023-05-07 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by mjskay** [comment]
This is (currently) the expected behavior, though I may be willing to be convinced otherwise. Cases are:

1. Unless I'm misremembering ggplot will convert that to a double so ggdist won't be able to detect it's an int
2. An integer rvar is treated as a discrete variable, so you get a histogram
3. When you add 0 (a double) you convert the underlying draws to double. Try adding 0L

One option might be for us to use rlang::is_integerish to detect case 3 but I think sticking with the explicit types is probably best...

This probably needs better documentation.

**Comment by mattansb** [comment]
> Unless I'm misremembering ggplot will convert that to a double so ggdist won't be able to detect it's an int

That is very weird! Why do they do that?

Is there a way to control if the passed rvar is treated as an integer (other than adding 0 or multiplying by 1...)?
If so, might be also useful to override (by the user) in both direction - treating intergerish values as integers, or treating integer rvars as doubles.

**Comment by mjskay** [comment]
> > Unless I'm misremembering ggplot will convert that to a double so ggdist won't be able to detect it's an int
> 
> That is very weird! Why do they do that?

Dunno. Might have to do with scale functions? Happens before `setup_data` is hit inside a stat.

> Is there a way to control if the passed rvar is treated as an integer (other than adding 0 or multiplying by 1...)?
If so, might be also useful to override (by the user) in both direction - treating intergerish values as integers, or treating integer rvars as doubles.

If the draws are integers, it's treated as an integer, and if the draws are numeric/double, it is treated as a double, etc. So you can convert the underlying draws (via `draws_of()`) to the desired format to get the desired behavior. It can be a bit of a pain because you have to maintain the dimensions of the draws to do it. Something like this would coerce to integer, for example:

```r
draws_of(x) = array(as.integer(draws_of(x)), dim = dim(draws_of(x)))
```

The conversion to numeric/double is easier because there's a function for it:

```r
x = as_rvar_numeric(x)
```

Which suggests it would probably be good to have an `as_rvar_integer()` and `as_rvar_logical()` in {posterior} as well...

**Comment by mattansb** [comment]
That works for rvars - I wonder if there is a solution for an integer vector to be internally treated as an integer?

**Comment by mjskay** [comment]
hmmm maybe try `scale_x_discrete()?`

**Comment by mattansb** [comment]
Yup, that works (but the opposite - adding `scale_x_continuous()` to the integer rvar - does not).

**Comment by mjskay** [comment]
Yeah, the rvar type is intended to be more self-contained --- it knows if it is discrete or not. So I think I'm okay with that. `as_rvar_integer()` and `as_rvar_logical()` are now in the dev version of posterior, so it should be easy enough to indicate what is desired with rvars in the future.

Thanks for raising this!
