### ISSUE TITLE
Split Violin Plots

### ISSUE THREAD

**Issue by Bramdiamond** [mjskay/ggdist#181]
Just came across `ggist` and I absolutely love it!

Is there a work around for implementing a split slab-interval plot? I would like to display two groups on the same plot to make comparisons easier and save room.

I'm hoping to recreate something like [this](https://rawgit.com/TomKellyGenetics/vioplot/vignettes/vignettes/violin_split.html) but only using `ggdist` if possible!

![image](https://github.com/mjskay/ggdist/assets/34584069/3dd9f7b3-0121-4b78-b24d-5d0f1cff0f5a)

Cheers,
Bram

**Comment by mjskay** [comment]
Sure, the simplest way is probably to map the subgroup the determines the side onto the `side` aesthetic, and then use `scale_side_mirrored()`:

```r
set.seed(1234); 
data.frame(y = rnorm(600, c(1,2)), group = c("a","b","c"), subgroup = c("d","e")) |> 
  ggplot(aes(x = group, y = y, fill = subgroup, side = subgroup)) + 
  stat_slab() +
  scale_side_mirrored()
```
![image](https://github.com/mjskay/ggdist/assets/6345019/112411c4-a29c-4884-9bd6-398c0dda1afb)

To fix the overlaps, just set `scale` to something less than `0.5`, so that the slabs take up 50% (or less) of the space:

```r
set.seed(1234); 
data.frame(y = rnorm(600, c(1,2)), group = c("a","b","c"), subgroup = c("d","e")) |> 
  ggplot(aes(x = group, y = y, fill = subgroup, side = subgroup)) + 
  stat_slab(scale = 0.5) +
  scale_side_mirrored()
```
![image](https://github.com/mjskay/ggdist/assets/6345019/c78bc5e2-70cb-47cf-b5a4-1e5720fcf4b0)

Then it's a question of the intervals... by default, they would overlap each other; e.g. if you just used stat_slabinterval:

```r
set.seed(1234); 
data.frame(y = rnorm(600, c(1,2)), group = c("a","b","c"), subgroup = c("d","e")) |> 
  ggplot(aes(x = group, y = y, fill = subgroup, side = subgroup)) + 
  stat_slabinterval(scale = 0.5) +
  scale_side_mirrored()
```
![image](https://github.com/mjskay/ggdist/assets/6345019/078e8716-8039-4c89-98db-c6fff0859295)

So a better approach would be to use a separate `stat_pointinterval` layer. This gets a bit hairy as you have to set the `width` so that they dodge an appropriate distance, and also adjust the starting point of `scale_side_mirrored()` so that the intervals and the slabs dodge to the same side. I also change the point shape to `21` to get the filled-in look on the point:

```r
set.seed(1234); 
data.frame(y = rnorm(600, c(1,2)), group = c("a","b","c"), subgroup = c("d","e")) |> 
  ggplot(aes(x = group, y = y, fill = subgroup, side = subgroup)) + 
  stat_slab(scale = 0.5) +
  stat_pointinterval(aes(point_fill = subgroup), shape = 21, position = "dodge", width = 0.1) +
  scale_side_mirrored(start = "topleft")
```
![image](https://github.com/mjskay/ggdist/assets/6345019/121b1196-0817-483e-9aae-e0bb85e9e91d)

**Comment by mjskay** [comment]
Actually, another way to make sure things line up occurred to me:

```r
set.seed(1234); 
data.frame(y = rnorm(600, c(1,2)), group = c("a","b","c"), subgroup = c("d","e")) |> 
  ggplot(aes(x = group, y = y, fill = subgroup, side = subgroup)) + 
  stat_slab(position = "dodge", justification = 0.5) +
  stat_pointinterval(position = "dodge", width = 0.1) +
  scale_side_mirrored(start = "topleft") 
```
![image](https://github.com/mjskay/ggdist/assets/6345019/66136433-e399-4244-88a4-172b626e699a)

The `width = 0.1` on stat_pointinterval works because the default setting of `scale` on `stat_slab` is `0.9`. So that should be robust in making the intervals and slabs line up...

**Comment by Bramdiamond** [comment]
This is perfect! Thank you very much.
