### ISSUE TITLE
fixed width alternative to `smooth_bar`

### ISSUE THREAD

**Issue by steveharoz** [mjskay/ggdist#190]
I've run into two limitations with `smooth_bar`:
1. Some columns of dots are often not as tall as the rest of the bar.
2. The ordering of the dots, when colored or shaped, goes from left to right, which is not an ideal stacking order.

```r
# make some data
df = tibble( 
  condition = rep(LETTERS[1:2], each=100), 
  color = c(rbinom(100, 1, .5), rbinom(100, 1, .9)) %>% factor()
) %>% 
  # order by color
  arrange(desc(color))
```

```r
# plot with smooth_bar
ggplot(df) +
  aes(x = condition, fill = color, group = 1) +
  geom_dots(color=NA, smooth = smooth_bar)
```
![image](https://github.com/mjskay/ggdist/assets/2257540/0a716bfe-7770-4488-a8b0-fb7d1467d2cc)

I made an alternative "bar" smoothing function which addresses both of those issues. But it introduces different limitations, so I thought I'd discuss it here before making a PR.

```r
# a smoother that tries to make a bar with a fixed width of columns
# it also orders the dots from bottom to top instead of side to side
# column_count: number of columns of dots per bar
# width: proportion of bar width relative to total space per bar
smooth_bar_fixed = function(x, column_count = 5, width = 0.7, ...) {
  if (missing(x)) return(partial_self("smooth_bar_fixed"))
  if (length(x) < 2) return(x)

  x_width = resolution(x, zero = FALSE) * width
  split(x, x) = lapply(split(x, x), function(x) {
    column_offsets = ppoints(column_count, 0.5) - 0.5
    column_offsets[(seq_along(x)-1) %% column_count + 1] * x_width + x[[1]]
  })
  x
}
```

Example use of `smooth_bar_fixed()`:
```r
ggplot(df) +
  aes(x = condition, fill = color, group = 1) +
  ggdist::geom_dots(color=NA, smooth = smooth_bar_fixed)
```
![image](https://github.com/mjskay/ggdist/assets/2257540/1a6b6a6e-42d3-4291-9aef-fda42110c28a)

However, it has its own limitations
1. The horizontal spacing between the dots isn't tight, unlike the vertical spacing. Perceived grouping might be effected. It's fixable, but the user has to fidget with a bunch of parameters like x-axis scale to make it better.
2. If there is not enough horizontal space for the `column_count`, it's a mess. See below:  

```r
tibble( 
  condition = rep(LETTERS[1:8], each=100), 
  color = c(rbinom(700, 1, .5), rbinom(100, 1, .9)) %>% factor()
) %>% 
  arrange(condition, color) %>% 
  ggplot() +
    aes(x = condition, fill = color, group = 1) +
    ggdist::geom_dots(color=NA, smooth = smooth_bar_fixed)
```
![image](https://github.com/mjskay/ggdist/assets/2257540/ccc824a7-8f2e-41ca-86f8-db63c8f642a1)

Thoughts? If you're ok with adding `smooth_bar_fixed()`, I can amend the docs and write up a PR.

**Comment by mjskay** [comment]
Yeah this is a good idea. The binwidth issue suggests to me that the best solution might be to move where smooths are applied in the rendering pipeline so that binwidth can be passed to the smoother. Then the user wouldn't need to do that manually.

Conceptually this should be possible, but might be a bit annoying to finagle...

**Comment by mjskay** [comment]
Sooo, I tried moving where smooths are applied in the pipeline and that won't work for a variety of reasons, including that the smooths have to be before data are transformed into physical units so that parameters to smooths can be specified in data units by the user. Basically, it would be a complete mess to try to move smooths late enough in the pipeline that the `binwidth` can actually be passed to them. If you're curious, there's now a branch (`smooth_dots_with_binwidth`) that contains a version of `smooth = "bar"` that has better layout, but which is broken in various other ways due to problems created by moving smooths later in the pipeline.

So I think the right solution to this is actually to introduce a new `layout` and to get rid of `smooth_bar()` altogether. That should allow all of the desired properties for bars (automatic bin widths, correct ordering, compact layout without gaps, etc). I should be able to take the actually-useful code from the `smooth_dots_with_binwidth` branch and use it to make a good bar layout. Will post here to get your thoughts on that when it is coming along.

**Comment by mjskay** [comment]
K, current attempt can be played with using `layout = "bar"` on the `dev` branch. 

On your example (slightly modified; note use of the `order` aesthetic to get stacking):

```r
tibble( 
  condition = rep(LETTERS[1:8], each=100), 
  g = c(rbinom(700, 1, .5), rbinom(100, 1, .9)) %>% factor()
) %>% 
  ggplot() +
    aes(x = condition, fill = g, group = NA, order = g) +
    ggdist::geom_dots(color = NA, layout = "bar")
```
![image](https://github.com/mjskay/ggdist/assets/6345019/3c16b3b3-3d9e-4a3d-8cb9-f9621c7adbee)

And with bars with different n:

```r
data.frame(
  x = factor(c(rep(1:5, times = 5:1 * 11), 6, 6, 7)),
  g = c("a","b")
) %>%
  ggplot(aes(x, fill = g, group = NA, order = g)) +
  geom_dots(layout = "bar")
```
![image](https://github.com/mjskay/ggdist/assets/6345019/3c05397c-2421-464a-8aa2-230e74d1faed)

Thoughts?

**Comment by steveharoz** [comment]
👍
