### ISSUE TITLE
Stan distribution functions

### ISSUE THREAD

**Issue by jmgirard** [mjskay/ggdist#21]
I love the new `stat_dist_halfeye()` function. However, I think the current approach of matching stan distribution names to existing R functions (see below) may not be ideal. In some cases, the R function differs from the stan function in argument names, orderings, and even parameterizations. 

https://github.com/mjskay/tidybayes/blob/ed254b9920e8407536f3f2e5f7f4b034e85a0df3/R/parse_dist.R#L150-L167

To address this issue, I have been creating an R function for each stan distribution function that remains true to the stan function. See my progress at [github.com/jmgirard/standist](https://github.com/jmgirard/standist).

I wonder if you might consider using these functions in the lookup table above (similar to what is already being done for `brms::student_t()`), or permitting me to do so via PR. If you are interested, I would be open to either importing from standist or rolling this project into tidybayes.

On a related note, in that same standist repo linked above, I am working on easy single-line function calls to visualize stan distributions (for pedagogical purposes and for selecting priors). Something like `viz("student_t(3, 0, 10)")` or `viz("student_t", arg1 = seq(1, 10, 2), arg2 = 0, arg3 = 1)`. I have some basic implementation of this using `ggplot2::stat_function()` but I think it'd be more robust and flexible to use your `tidybayes::stat_dist_halfeye()` function. Any interest in collaborating on this?

**Comment by mjskay** [comment]
Yeah, there's a couple of things to consider here in light of #14.

I suspect long-term my plan is to rethink `parse_dist()` a bit and have it output distribution vectors a la #14 rather than the string-plus-args approach. If https://github.com/mitchelloharawild/distributional/issues/30 is implemented than I could imagine using it to wrap arbitrary stan distributions from brms priors and outputting those. 

On the other hand, it may then be the case that `ggdist` isn't the right place for the solution to this problem. Another way forward would be to petition @paul-buerkner to put a function in brms that outputs {distributional} vectors of brms priors, possibly using the {standist} package. Then those vectors would automatically be supported by the upcoming version of {ggdist} without having to use `ggdist::parse_dist()` at all (the `stat_dist_...` geoms on the dev branch of ggdist can already plot such objects). Would be curious what @paul-buerkner thinks about something like that?

**Comment by paul-buerkner** [comment]
I have not yet looked at this in detai. Would you mind opening an issue on the brms github tracker?

**Comment by mitchelloharawild** [comment]
The {distributional} package can now wrap arbitrary distributions (https://github.com/mitchelloharawild/distributional/issues/30).
With the recent addition of {distributional} support in {ggdist}, it should now be possible to plot arbitrary distributions:

``` r
library(ggplot2)
library(dplyr)
library(ggdist)
library(brms)
library(distributional)

tribble(
  ~ group, ~ dist,
  "Normal", dist_normal(mu = 0, sigma = 1),
  "Skewed", dist_wrap("skew_normal", package = "brms", mu = 0, sigma = 1, alpha = 10)
) %>%
  ggplot(aes(x = group, dist = dist, fill = group)) +
  stat_dist_eye(position = "dodge")
```

![](https://i.imgur.com/b5TEpvU.png)

<sup>Created on 2020-07-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mjskay** [comment]
I think this problem is basically solved from the {ggdist} perspective: `parse_dist()` has (for awhile now) supported arbitrary distributions in via `distirbutiona::dist_wrap()`, and passes down the `package` argument. Thus, if someone wanted to support an arbitrary set of distributions defined in some other package or environment, they can pass that package or environment to `parse_dist()` and then it should find the distributions and set up the `.dist_obj` object correctly.
