### ISSUE TITLE
Conditional slab fill for priors

### ISSUE THREAD

**Issue by ASKurz** [mjskay/ggdist#210]
I'm trying to depict priors with conditional fill based on the `.width` intervals, and I'm at a loss. It looked like maybe I want some version of `scale_slab_fill_discrete()` or `scale_slab_fill_continuous()`, but I can't seem to get it to work nice. For example, here's one of my [many] naive attempts to use the `Blues` color palette.

 ```{r}
c(prior(normal(100, 10), class = Intercept),
  prior(exponential(0.1), class = sigma)) %>% 
  parse_dist() %>%

  ggplot(aes(y = prior, dist = .dist, args = .args, slab_fill = after_stat(level))) +
  stat_dist_halfeye(.width = c(.5, .95)) +
  scale_slab_fill_discrete("Blues")
```

Show me the way.

**Comment by mjskay** [comment]
You can use the `aesthetics` parameter of `scale_fill_brewer()` and the like to do this:

```r
c(prior(normal(100, 10), class = Intercept),
  prior(exponential(0.1), class = sigma)) %>% 
  parse_dist() %>%

  ggplot(aes(y = prior, dist = .dist_obj, slab_fill = after_stat(level))) +
  stat_halfeye(.width = c(.5, .95)) +
  scale_fill_brewer(palette = "Blues", aesthetics = "slab_fill")
```
![image](https://github.com/mjskay/ggdist/assets/6345019/fbb70b5b-c588-4a8f-90a5-66427ba46f60)


I also changed `dist = .dist, args = .args` to the simpler `dist = .dist_obj` (since the old syntax is no longer recommended as it can't handle truncation, and the new syntax is simpler) and `stat_dist_halfeye()` to just `stat_halfeye()` (the `..._dist_...` stats are also deprecated and will probably get a warning at some point in the future).

The other way to go if the sub-geometry aesthetics are being bothersome (they don't always work with some ggplot2 things that try to give helpful errors but which are actually false positives) is to either use `fill` directly (since it is the same as `slab_fill` for halfeye):

```r
c(prior(normal(100, 10), class = Intercept),
  prior(exponential(0.1), class = sigma)) %>% 
  parse_dist() %>%

  ggplot(aes(y = prior, dist = .dist_obj, fill = after_stat(level))) +
  stat_halfeye(.width = c(.5, .95)) +
  scale_fill_brewer(palette = "Blues")
```
![image](https://github.com/mjskay/ggdist/assets/6345019/295b5635-612c-4b94-bfe8-95134c0665d1)

Or to decompose the composite halfeye geometry into a slab and a pointinterval; then you can more easily target specific aesthetics on specific sub-geometries:

```r
c(prior(normal(100, 10), class = Intercept),
  prior(exponential(0.1), class = sigma)) %>% 
  parse_dist() %>%

  ggplot(aes(y = prior, dist = .dist_obj)) +
  stat_slab(aes(fill = after_stat(level)), .width = c(.5, .95)) +
  stat_pointinterval(.width = c(.5, .95)) +
  scale_fill_brewer(palette = "Blues")
```
![image](https://github.com/mjskay/ggdist/assets/6345019/f2b80164-894b-4440-a135-7c2bb14a0d23)

**Comment by ASKurz** [comment]
This is really helpful. Thanks!
