### ISSUE TITLE
Width legend: could default title and labels be improved?

### ISSUE THREAD

**Issue by davidhodge931** [mjskay/ggdist#211]
Great package!

For slabinterval legends, the default title defaults to "-.width" and the default labels have a "-" sign in front of them.

I was wondering if these could made more interpretable. 

Maybe like how ggdensity does it with the default title called "probs" and the default labels being as %'s? See image below

``` r
library(tidyverse)
library(ggdist)
library(distributional)

data.frame(
  distribution = c("Gamma(2,1)", "Normal(5,1)", "Mixture"),
  values = c(
    dist_gamma(2, 1),
    dist_normal(5, 1),
    dist_mixture(dist_gamma(2, 1),
                 dist_normal(5, 1),
                 weights = c(0.4, 0.6))
  )
) |>
  ggplot() +
  stat_slabinterval(mapping = aes(y = distribution, dist = values), show.legend = TRUE)
```

![](https://i.imgur.com/gE65i9V.png)

<sup>Created on 2024-01-25 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

![image](https://github.com/mjskay/ggdist/assets/55065152/9587c553-9f40-415f-8a78-5f5ea2cbe0b8)

**Comment by mjskay** [comment]
You can do this using the `levels` computed variable (e.g. with `aes(size = after_stat(level))`). I am a bit reluctant to change it by default since it would subtly change a lot of existing plots, though perhaps it would be worth it.... I would want to see how much of existing things it breaks.

There is an existing issue (#156) where I have been pondering this.

**Comment by davidhodge931** [comment]
I'd encourage you to make a change here - it'd totally be worth it
