### ISSUE TITLE
using after_stat in stat_halfeye to fill distribution by aes value

### ISSUE THREAD

**Issue by yonisidi** [mjskay/ggdist#248]
should it be possible to fill a distribution cutoff by a column in the input tibble?

```r
 plot_tbl <- tibble::tibble(
    dist = "lnorm", 
    label = c('>=3', '>=4',  '>=6', '>=8'),
    cutoff = c(3, 4, 6, 8),
    logmean = c(log(7),log(9), log(12), log(18)), 
    logsd = log(3.5)
  )
```

```r
plot_tbl |>
    ggplot() +
    ggdist::stat_halfeye(aes(
      y = factor(label), dist = dist, arg1 = logmean, arg2 = logsd,
      fill = after_stat(x < cutoff)), show.legend = FALSE) +
    scale_x_log10(breaks = 10^seq(-5,7, by = 2))
```

```r
> Error in FUN(X[[i]], ...) : object 'cutoff' not found
```

**Comment by mjskay** [comment]
The reason this doesn't work the way you'd think is because in ggplot2 expressions in `after_stat()` are evaluated on a different data frame later in the pipeline --- after stats have been computed. This data frame may not (and in the case of ggdist, does not) even have the same shape as the original data.

Fortunately when ggdist stats compute derived values (like densities and intervals) it will replicate other columns in the mapped  data frame over the generated rows so that they are still there later in the pipeline. 

The upshot of all this is that you can do what you want so long as you pass the `cutoff` value into some (possibly made-up) aesthetic so that it is available after stats have been computed. For example:

```r
plot_tbl |>
    ggplot() +
    ggdist::stat_halfeye(aes(
        y = factor(label), dist = dist, arg1 = logmean, arg2 = logsd, 
        cutoff = cutoff,  # make sure cutoff values get passed through to after_stat()
        fill = after_stat(x < cutoff)), show.legend = FALSE) +
    scale_x_log10(breaks = 10^seq(-5,7, by = 2))
## Warning message:
## In layer_slabinterval(data = data, mapping = mapping, stat = StatSlabinterval,  :
##   Ignoring unknown aesthetics: cutoff
```
![image](https://github.com/user-attachments/assets/8d210d68-c362-46a5-972f-33daf4f56c87)

You do get a spurious warning about unknown aesthetics, which can be ignored. I just realized from investigating this that there is a `check.aes` argument to `layer()` that can suppress this warning but which ggdist currently doesn't pass down, so I will fix that now.

**Comment by mjskay** [comment]
Now on the dev branch, with `check.aes = FALSE`:

```r
plot_tbl |>
    ggplot() +
    ggdist::stat_halfeye(aes(
        y = factor(label), dist = dist, arg1 = logmean, arg2 = logsd, 
        cutoff = cutoff,  # make sure cutoff values get passed through to after_stat()
        fill = after_stat(x < cutoff)), show.legend = FALSE, check.aes = FALSE) +
    scale_x_log10(breaks = 10^seq(-5,7, by = 2))
```
![image](https://github.com/user-attachments/assets/8d210d68-c362-46a5-972f-33daf4f56c87)

**Comment by yonisidi** [comment]
Very nice! Ty!

**Comment by mjskay** [comment]
np!
