### ISSUE TITLE
Add stat_ribbon()

### ISSUE THREAD

**Issue by mitchelloharawild** [mjskay/ggdist#48]
Much like `stat_dist_lineribbon()`, but without the line. Alternatively, `stat_dist_lineribbon()` could be extended to support 0 or >1 functions to allow 0 or more than 1 line.

This will be used by fabletools v0.4.0 as `distributional::geom_hilo_ribbon()` gets deprecated.

---

The motivating example for this is showing both mean and median forecasts for asymmetric distributions, such as the Log-normal distributions below.

``` r
library(fable)
#> Loading required package: fabletools
eggs <- as_tsibble(fma::eggs)
eggs %>% 
  model(ETS(log(value))) %>% 
  forecast(h = 100) %>% 
  autoplot(eggs, point_forecast = tibble::lst(mean, median))
```

![](https://i.imgur.com/Su0uIRU.png)

<sup>Created on 2021-01-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mjskay** [comment]
Good idea! Thoughts:

- I like the simplicity of `stat_dist_ribbon()`. For consistency with the ggdist naming scheme I would probably also want to add a `stat_ribbon()` for sample data. My only concern is that there would then be no corresponding `geom_ribbon()` (or more correctly, it wouldn't be `ggplot2::geom_ribbon()` but rather `ggdist::geom_lineribbon()` with some setting to suppress the line), which might be confusing to people... it breaks the naming scheme in the rest of ggdist a bit.
- Because of the organization of the data tables generating by `stat_dist...` (specifically that the points and intervals are in the same rows, not separate rows), generating an arbitrary number of lines not tied to the intervals in some way would probably be messy. I'm not necessarily averse to changing that, but it's a big change that touches a lot of things, and I'd need to be convinced it's worth it.
- Given that, I'd probably prefer `stat_dist_ribbon()` and/or an option in `stat_dist_lineribbon()` to turn off the line (probably `stat_dist_lineribbon(show_line = FALSE)` to mirror the options in the slabinterval geoms/stats.

Probably adding `show_line` to `geom_lineribbon()` is the starting point, then adding `stat_ribbon()` and `stat_dist_ribbon()` as aliases if desired. Would that cover your use cases?

**Comment by mitchelloharawild** [comment]
Sounds good to me, removing the line via an argument should work.

Regarding stat_ribbon(), how does this differ from using stat_dist_ribbon()
with a dist_sample()? I suspect if there exists a conflict, it would only
be from the data preprocessing steps and not the geometry (unless the geom
should be called geom_multiribbon() or something). I haven't thought about
this much yet, just writing some ideas down before I sleep.

**Comment by mjskay** [comment]
> Regarding stat_ribbon(), how does this differ from using stat_dist_ribbon()
with a dist_sample()?

It doesn't differ that much, really, but it saves a data transformation step or two for users. It's also a workflow that a lot of people use, since it was the original workflow from tidybayes before ggdist got split off, and it's one I want to continue supporting across all geoms/stats. It is also currently faster, until `density()` for distributional objects is vectorized (since the KDE for each variable is only calculated once instead of once per variable per x position).

**Comment by mjskay** [comment]
(sidebar: is there a timeline you are planning to hit that depends on this change? I am steeped in teaching prep and grad app reviews at the moment, so I might not have much time for changes for the two weeks or so)

**Comment by mitchelloharawild** [comment]
> It doesn't differ that much, really, but it saves a data transformation step or two for users. It's also a workflow that a lot of people use, since it was the original workflow from tidybayes before ggdist got split off, and it's one I want to continue supporting across all geoms/stats. 

I agree that working with a long format data structure is more familiar and can be better suited to a ggplot workflow here.

> It is also currently faster, until `density()` for distributional objects is vectorized (since the KDE for each variable is only calculated once instead of once per variable per x position).

I'll make that a priority for `{distributional}`.

> (sidebar: is there a timeline you are planning to hit that depends on this change? I am steeped in teaching prep and grad app reviews at the moment, so I might not have much time for changes for the two weeks or so)

`{distributional}` can hold onto the `{ggplot2}` dependency until you have time, so no rush here. There's plenty of other things to work on in the meantime.

**Comment by mjskay** [comment]
> I'll make that a priority for {distributional}.

Sweet thanks! It occurred to me I dumped a bunch of unsolicited opinions about formats for multivariate densities into that other thread awhile back :). To be honest, after reflecting on it for awhile I think as long as there's a simple way to get vectorized density values from a single distribution (i.e. a {distributional} vector of length one) it'll probably work well for my use cases.

> {distributional} can hold onto the {ggplot2} dependency until you have time, so no rush here. There's plenty of other things to work on in the meantime.

Cool, I've added this issue to the Next Release milestone.

**Comment by mitchelloharawild** [comment]
Revisiting this, I can remove the line with a bit of a hack - setting the colour aesthetic to be NA or transparent in some way.
So in that sense it is less urgent, but would certainly be nice to have :)

**Comment by mjskay** [comment]
Yeah, setting color to `NA` is probably the preferred method in the short term. Do let me know if you run into any weirdness with that.

Long term, I am in the midst of restructuring essentially the entire stat/geom codebase on the `unify-dist` branch for #83, after which it will be *much* easier to add and maintain additional shortcut stats/geoms without a pile of boilerplate (courtesy #106). Then it should be trivial to implement a `stat_ribbon()`.

**Comment by mjskay** [comment]
The `stat_ribbon()` shortcut stat is now on master.
