### ISSUE TITLE
stat_dist_slab CDF of a log-normal doesn't reach 1.0 

### ISSUE THREAD

**Issue by bearloga** [mjskay/ggdist#52]
Hiya! Love this package and really appreciate all the work you've put into it. So thank you very much for it, Matthew!

While working with @Dpananos on a project, we came across an peculiar behavior. I'm not sure if it's something we're missing on our end or if it's a bug with {ggdist} (or maybe everything is working as intended and this is just an interesting edge case), but we're plotting CDF of lognormal with `stat_dist_slab()`:

``` r
library(ggplot2)
library(ggdist)
library(distributional)
library(tidyverse)

example <- tibble(
    mu = c(8.1, 7.9),
    sigma = c(1.95, 2.05)
)
ggplot(aes(y = 0, color = "mcmc draw"), data = example) +
    geom_hline(yintercept = plnorm(1e6, 8, 2), linetype = "dashed") +
    stat_dist_slab(
        aes(dist = "lnorm", arg1 = mu, arg2 = sigma),
        fill = NA, slab_type = "cdf", limits = c(0, 1e6),
    ) +
    stat_dist_slab(
        aes(dist = "lnorm", arg1 = 8, arg2 = 2),
        fill = NA, slab_type = "cdf", color = "red", data = NULL
    ) +
    scale_color_manual(
        name = NULL, values = c("mcmc draw" = "black"), guide = FALSE
    ) +
    scale_x_log10(breaks = 10 ^ (0:6)) +
    scale_y_continuous(breaks = seq(0, 1, 0.05), minor_breaks = NULL)
```

and the slab curves at x=1e6 don't reach up to where they should:

![cdf](https://user-images.githubusercontent.com/1807519/105737499-0565d600-5f04-11eb-8a25-f62097381bd6.png)

Weird, right?

**Comment by mjskay** [comment]
Ah yup, this is due to a bit of a conflict in expected use cases for the slabinterval geometries. The short answer is you need to set `scale = 1`.

The long answer is, the defaults were really designed for the style of plots where you might want multiple slab associated with different factors on the y axis (say). The result is the need for a gap between the "slabs" so they don't touch, and this is handled by the `scale` parameter, the default of which is `0.9`. 

Because the original use cases I envisioned for slabs don't typically involve the numerical axis labels, this hasn't been a huge issue, but it's clear that I need some clarity in the documentation and some examples cover use cases like yours.

**Comment by bearloga** [comment]
Ah! Thank you so much for the explanation @mjskay!

**Comment by mjskay** [comment]
you're welcome!

**Comment by mjskay** [comment]
I believe this should be clarified by the height/scale diagram that will be at the top of the slabinterval vignette in the next release, so closing this now.
