### ISSUE TITLE
Mode returned negative value for all positive vector

### ISSUE THREAD

**Issue by Famondir** [mjskay/ggdist#57]
Hi,
I got an interesting issue today with the Mode() function. I had a large double vector (10 million numbers) as input. It hold MCMC draws for odds ratios and thus where all >= 0. Any value was unique. Mode() then returned a negative value. This one resulted from the density() function and was the first value in density(z)$x. 

Using the tabulate(z) function will give you the first number which was not in the HDI but nevertheless at least positive.

I came up with this approach to get a value that seems to be drawn more often (approximately):
`get_mode <- function(v, signs = 23) {
  uniqv <- unique(v)
  tab <- tabulate(match(v, uniqv))

  if(max(tab) == 1 & is.numeric(v)) {
    if (signs == 23) message(paste0('There was a draw. There were ', sum(tab[tab == max(tab)]), ' modes.'))

    v <- signif(v, signs-1)

    return(get_mode(v, signs-1))
  } else {
    modus <- uniqv[which.max(tab)]
    if (signs != 23) message(paste0('No draws taking into account ', signs, ' signs.'))
  }

  return(modus)
}`

I don't know if this is something Mode() should do by default. Another way would be throw an error or print a message that the count of the value is only 1 and thus there was a draw.

**Comment by mjskay** [comment]
Hmm, sounds problematic... could you create a [reprex](https://www.tidyverse.org/help/) with example data showing the problem? That would help me diagnose it.

Thanks!

**Comment by Famondir** [comment]
I was able to sample a much smaller double vector that reproduces the behavior:
`c(8104.6708071, 2.1980919, 0.7569663, 6.2002883, 3.2318454, 2.5476119, 1.3982123, 2.9978539, 1.3471747, 2.2059935)`

Seems like occurence of some big numbers can result in a negative density() entry.

**Comment by mjskay** [comment]
Ah I see what's happening. Some things have conspired to create problems: the mode estimator for a continuous variable we are using uses a kernel density estimator, which currently does not cut off at the bounds of the data (even though it should). That's an easy fix that will prevent negative numbers in this case.

That said, for your data it still doesn't give a great estimate of the mode. The reason is because for the density estimator we still need to pick a grid size, and given the range of your data, the default grid size is not good (in fact you don't get a good estimate of the mode on your data until the grid size is on the order of 30,000 points, which is a little ridiculous). I'm not inclined to change those defaults unless someone who knows a lot about mode estimation comes along and suggests a good general-purpose mode estimator. The [modeest](https://cran.r-project.org/package=modeest) package has a bunch but seemingly little guidance on their selection. My guess is their applicability depends on your data, which makes it hard to pick a generic one.

So:
- I've updated `Mode()` to at least use trimmed densities, which should solve the problem of getting numbers outside the range of the data. You will have to install the latest version from github to use it: `devtools::install_github("mjskay/ggdist")`. However the mode estimate in your case is still not great:

```r
library(ggdist)

x = c(8104.6708071, 2.1980919, 0.7569663, 6.2002883, 3.2318454, 2.5476119, 1.3982123, 2.9978539, 1.3471747, 2.2059935)

Mode(x)
## [1] 0.7569663
```


- I'd recommend looking at mode estimators in {modeest} to see if some of those serve your needs better. If you are using `mode_hdi()` currently you can define your own `point_interval` function that uses a different mode estimator by doing something like this:

```r
library(ggdist)
library(modeest)

x = c(8104.6708071, 2.1980919, 0.7569663, 6.2002883, 3.2318454, 2.5476119, 1.3982123, 2.9978539, 1.3471747, 2.2059935)

# define a point_interval function using the hsm (half sample mode) estimator from modeest
hsm_hdi = function(...) point_interval(..., .point = hsm, .interval = hdi)

hsm_hdi(x, .width = 0.66)
##          y     ymin     ymax .width .point .interval
## 1 2.202043 1.347175 3.231845   0.66    hsm       hdi
```

Hope that helps!

**Comment by Famondir** [comment]
Thanks a lot. I'll definitly have a look at that package and look for the most fitting function there. I'm curius if some of them behave like my own function.^^

I think the truncation is a good thing to prevent most unforseen issues. Totally agree that some research on mode implementation would be good instead of just hacking some naive approach. Big thanks for the hint how to define a custom point_interval. Great and fast support!

**Comment by Famondir** [comment]
The hsm seems to fit best for my data structure and my understandings on how a mode function should work. Thanks again. :)

**Comment by mjskay** [comment]
You're welcome, glad I could help!
