### ISSUE TITLE
Scale fill ramp override aes

### ISSUE THREAD

**Issue by Ari04T** [mjskay/ggdist#66]
Is there a way to manually control the colors for the colour/fill ramp discrete legend? Right now, if I try to override them manually, I do not get the same colour 3 times but instead I get the following.
```
scale_fill_ramp_discrete(range = c(1, 0.2), na.translate = FALSE) +    
guides(
        fill_ramp = guide_legend(override.aes = list(fill = c("red",
                                                              "red",
                                                              "red")))
    ) 
```
![image](https://user-images.githubusercontent.com/7259598/114292990-85f69600-9a60-11eb-98d6-050fcc71966a.png)

**Comment by mjskay** [comment]
Ah, that's because the fill_ramp aesthetic is what the legend is showing, so the color ramp (from red to white) is being applied to the legend. If you just override the fill aesthetic the fill_ramp is still applied.

What was the output you were looking for?

**Comment by Ari04T** [comment]
Makes sense. I am happy with the way the color ramp looks on the plot with the current parameters (range 1, 0.2), but the legend with the default format is a little bit to faint, especially for the 95% interval. As you can see, I use a grey background so the original 95% fill basically blends with the background. I just wanted to manually adjust that key fill to make it a bit more visible.

**Comment by mjskay** [comment]
Ah makes sense. Is the plot background also gray? Assuming this is the ggplot default (`theme_gray()`), I'd first start by changing the base blend color in the color ramp to `"gray92"` (the background color of that theme) so that the colors are being blended with the background gray instead of white. I played around a bit with that, the range, and changing the foreground to a red from  [colorbrewer](https://colorbrewer2.org/#type=sequential&scheme=BuGn&n=3) and came up with this:

```r
dist_df = tibble(
  group = c("a","b","c"),
  mean = 1:3,
  sd = 1
)
dist_df %>%
  ggplot(aes(x = group, dist = dist_normal(mean, sd))) +
  stat_dist_interval(aes(color_ramp = stat(level)), color = "#de2d26") +
  scale_color_ramp_discrete(from = "gray92", range = c(0.3,1)) +
  theme_gray()
```
![image](https://user-images.githubusercontent.com/6345019/114332291-8e57db00-9b0b-11eb-85e1-15b81f4dca7d.png)

it could probably be tweaked still, but does something in that direction help?

**Comment by mjskay** [comment]
Hope this helped! Closing this for now but let me know if you have any issues.
