### ISSUE TITLE
Default value of binwidth in geom_dots

### ISSUE THREAD

**Issue by Rishabh261998** [mjskay/ggdist#76]
Can anyone please tell me how does `geom_dots` calculate the default `binwidth`? I am unable to find it. Thanks

**Comment by mjskay** [comment]
Given the plot size and the `scale` parameter, ggdist uses binary search to find the number of bins (and corresponding bin width) that will fit into the available space (where `scale = 1` means "fill up all the space between points on the y axis" when plotting horizontally). This is a rough sketch of what it does; there are a few other heuristics and corner cases involved (e.g. It has a minimum number of bins determined by some histogram binning alrogithms to try to prevent things from getting too ridiculous looking with a very small number of bins if there's a lot of vertical space available).

Does that help? Did you have a more specific question about it?

**Comment by Rishabh261998** [comment]
Yes, it helps, just wanted to know how do you find the binwidth from the number of bins because for Wilkinson's algorithm I am not sure if binwidth = range/(number of bins) holds or does it?. Also, it would be great if you could provide the file path where this is implemented so that I can go a bit deeper. Thanks

**Comment by mjskay** [comment]
> Yes, it helps, just wanted to know how do you find the binwidth from the number of bins because for Wilkinson's algorithm I am not sure if binwidth = range/(number of bins) holds or does it?

It doesn't quite necessarily, but for the purposes of the dynamic binning algorithm I roughly assume it does. This doesn't make a big difference because I have to run a (modified) Wilkinson binning algorithm to determine max bin height anyway, so really I'm just using number of bins as a discretization of bin width in the search (in fact the search itself is a bastardized binary search because it doesn't require number of bins to be an integer). Probably at some point I should just switch to optimizing binwidth directly, but the current approach has been working well enough (and quickly enough) that I haven't had the motivation to do that.

Your question is a bit serendipitous as I've been meaning to factor out the dynamic binning code to make it easier for others to use (see #77). Unfortunately until I do that the code is a bit tightly coupled with the dotplot drawing code; apologies :). See the [`makeContent.dots_grob()` function](https://github.com/mjskay/ggdist/blob/8818eaf8b9e7d3c267c330171733ba2af8ff260d/R/geom_dotsinterval.R#L33) and particularly [this part](https://github.com/mjskay/ggdist/blob/8818eaf8b9e7d3c267c330171733ba2af8ff260d/R/geom_dotsinterval.R#L109).

**Comment by Rishabh261998** [comment]
Thanks a lot
