### ISSUE TITLE
bug: position_dodge() adds a nudge to slab? 

### ISSUE THREAD

**Issue by bwiernik** [mjskay/ggdist#85]
I'm trying to use `position_dodge()` with `stat_dist_halfeye()` as well as other geoms (line and label). For some reason, doing this is adding a nudge offset to the distribution geom. I need to counteract that with a manual tweak of the position to get everything to line up correctly. See an example below:

``` r
library(ggplot2)
library(ggdist)
plot_data <- 
  tibble::tribble(
    ~Model, ~Parameter, ~Coefficient,  ~SE, ~CI_low, ~CI_high, ~df_error, ~linetype, ~nudge,
    "A",       "MZ",         0.41, 0.04,    0.33,     0.48,       530,  "dashed",   0.25,
    "A",     "Full",          0.4, 0.03,    0.35,     0.45,      1266, "twodash",   0.25,
    "B",       "MZ",         0.36, 0.04,    0.29,     0.44,       522,  "dashed",   0.25,
    "B",     "Full",         0.34, 0.03,    0.29,     0.39,      1256, "twodash",   0.25,
    "C",       "MZ",         0.34, 0.07,     0.2,     0.48,       Inf,  "dashed",   0.25,
    "C",     "Ereg",         0.28, 0.06,    0.16,     0.41,       Inf, "twodash",   0.25,
    "D",       "MZ",         0.31, 0.08,    0.15,     0.46,       Inf,  "dashed",      0,
  ) |> 
  dplyr::mutate(dplyr::across(Model:Parameter, forcats::as_factor))

base_plot <- plot_data |>
  ggplot() +
  aes(x = forcats::fct_rev(Model), y = Coefficient, ymin = CI_low, ymax = CI_high,
      label = Parameter, color = Parameter,
      group = linetype,
      dist = distributional::dist_student_t(df = df_error, mu = Coefficient, sigma = SE)
  ) +
  theme_classic() +
  guides(color = "none", linetype = "none") +
  labs(x = NULL, y = NULL) +
  coord_flip()

# looks right, with nudge
base_plot +
  geom_line(
    aes(linetype = linetype, color = dplyr::recode(Parameter, Ereg = "Full"), group = linetype),
    position = position_dodge(width = .5)
  ) +
  stat_dist_halfeye(
    aes(y = Coefficient, x = as.integer(forcats::fct_rev(Model)) + nudge,
        fill = after_scale(colorspace::lighten(color, .1))),
    position = position_dodge(width = .5),
    slab_alpha = .25
  ) +
  geom_label(
    fill = "white",
    position = position_dodge(width = .5)
  )
```

![](https://i.imgur.com/TGTQoxQ.png)

``` r
# looks wrong, no nudge
base_plot +
  geom_line(
    aes(linetype = linetype, color = dplyr::recode(Parameter, Ereg = "Full"), group = linetype),
    position = position_dodge(width = .5)
  ) +
  stat_dist_halfeye(
    aes(y = Coefficient, x = forcats::fct_rev(Model) ,
        fill = after_scale(colorspace::lighten(color, .1))),
    position = position_dodge(width = .5),
    slab_alpha = .25
  ) +
  geom_label(
    fill = "white",
    position = position_dodge(width = .5)
  )
```

![](https://i.imgur.com/i8BaYm2.png)

<sup>Created on 2021-07-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

Any idea if this could be fixed? 

(Also, last night, I was also having an issue at one point with the dodging going in the opposition direction with `stat_dist_halfeye()` as with `geom_line()` or `geom_label()` [I had to set `width = -.5` in `stat_dist_halfeye()`'s `position_dodge()`], but I'm not able to reproduce that now with this simple case--will look into some of the more complex plots I tried out.)

**Comment by mjskay** [comment]
ggdist currently does some unorthodox things to correct the alignment of intervals and slabs in position_dodge, and it's definitely possible there is a better way to do it :). Happy to take a look, though your reprex has some errors in it currently, can you update it? Thanks!

**Comment by bwiernik** [comment]
oops, sorry! fixed.

**Comment by bwiernik** [comment]
With two groups at a position, everything seems to be shifted down by .5 * width. Not sure the generalization

**Comment by mjskay** [comment]
hmmm yeah. This gets into code I was not wanting to touch :)

Basically I have to hack around the fact that position_dodge() is a bit weird in that it doesn't maintain the relative justification of x/y values and xmin/xmax/ymin/ymax values when dodging, so based on where things have been dodged to and the `justification` parameter I have to figure out where to position the slabs relative to the intervals. This is handled by a bunch of crap approximately here:

https://github.com/mjskay/ggdist/blob/de20d5ca28407f3f241f1d46617dfda9f87104fe/R/geom_slabinterval.R#L35-L53

I *think* it should be possible to adjust this to move the min/max around the center (x/y) instead of adjust the x/y. May also have to change some stuff here:

https://github.com/mjskay/ggdist/blob/de20d5ca28407f3f241f1d46617dfda9f87104fe/R/geom_slabinterval.R#L581-L587

It would probably break some old charts to fix this, but it is probably worth it. Ideally the fix should only break charts that use dodging.

**Comment by mjskay** [comment]
(this might also be totally unfixable without making a different version of position_dodge, I recall I either came to that conclusion or gave up when I originally was working on this problem, but I can't remember which)

**Comment by mjskay** [comment]
k i am attempting to fix this on the [fix-just](https://github.com/mjskay/ggdist/tree/fix-just) branch. Not sure how successful it is so far but you're welcome to take a look.

**Comment by mjskay** [comment]
Ah yup now I remember why this ended up the way it was --- plot bounds can be incorrect. I'll post some examples later when I have time. Possibly the solution will be to change how justifications are calculated but also provide a modified version of position_dodge that will work better in some cases.

**Comment by bwiernik** [comment]
That fix does work for my case here, but I do see how the slabs are ending up closer to the top of the panel and that might cause issues. 

Are you thinking the default would be the "plays well with others" dodge in the fix-just branch and the new one being an alternative if things turn out poorly with that?

**Comment by mjskay** [comment]
So, the issue is that position_dodge always moves the point (x or y depending on orientation, but let's say x here) to the center of the box the geom will be drawn in after dodging (xmin/xmax). The solution in the existing version of ggdist is to use the justification to move the interval relative to the slab:

```r
dist_df = tribble(
    ~group, ~subgroup, ~mean, ~sd,
    1,          "h",     5,   1,
    2,          "h",     7,   1.5,
    3,          "h",     8,   1,
    3,          "i",     9,   1,
    3,          "j",     7,   1
)
```

```r
dist_df %>%
  ggplot(aes(x = group, dist = dist_normal(mean, sd), fill = interaction(group,subgroup))) +
  stat_dist_halfeye(position = "dodge") +
  geom_rect(
    aes(xmin = group, xmax = group + 1, ymin = 2, ymax = 13, color = interaction(group, subgroup)), 
    position = "dodge", alpha = 0.1
  ) +
  geom_point(
    aes(x = group, y = 7.5, xmin = group, xmax = group + 1, color = interaction(group, subgroup)), 
    position = "dodge",
    shape = 1,
    size = 4
  ) +
  scale_fill_brewer(palette = "Set2") +
  scale_color_brewer(palette = "Dark2")
```
![image](https://user-images.githubusercontent.com/6345019/124150202-fa851380-da56-11eb-9089-3f3f5b7dab73.png)

This works but obviously means that points positioned using dodge won't line up correctly. The version on the fix-just branch instead moves the slab relative to the point position, which means things line up but can go outside the allotted area for the geom, hence the issues near plot edges:

```r
# same code, just running it on fix-just now
dist_df %>%
  ggplot(aes(x = group, dist = dist_normal(mean, sd), fill = interaction(group,subgroup))) +
  stat_dist_halfeye(position = "dodge") +
  geom_rect(
    aes(xmin = group, xmax = group + 1, ymin = 2, ymax = 13, color = interaction(group, subgroup)), 
    position = "dodge", alpha = 0.1
  ) +
  geom_point(
    aes(x = group, y = 7.5, xmin = group, xmax = group + 1, color = interaction(group, subgroup)), 
    position = "dodge",
    shape = 1,
    size = 4
  ) +
  scale_fill_brewer(palette = "Set2") +
  scale_color_brewer(palette = "Dark2")
```
![image](https://user-images.githubusercontent.com/6345019/124150558-4a63da80-da57-11eb-9da4-bf498aaeee62.png)

I'm honestly not sure the best solution. One option is to position slabs relative to the points like in the fix-just branch and add a "justified dodge", `position_justdodge()` or something like that, which could position the points correctly when dodging. Another might be to let people change the positioning approach with an option to the geom (I'm not a big fan of that though). I'm open to suggestions.

**Comment by bwiernik** [comment]
I think making `position_dodge()` follow the fix-just behavior and having an alternative `position_*()` function makes the most sense. The fix-just behavior works in a most cases and it plays nicely with other geoms if users want to layer. I think it also makes sense to avoid an anti-pattern by having the different behavior be associated with a different function (e.g., easier to explain in documentation that the new function has a different behavior than the explain that it is the regular behavior normally expected from `position_dodge()`).

It took me a while to realize how the word "justification" applied to the behavior (that you are left/bottom justifying the geoms to their bounding box, rather than center/middle justifying them). But I see it now. I think `position_dodgejust()` or `position_dodgejustified()` might be a little clearer? Maybe give both as an alias? This function could have a `just` argument ala `hjust` in some `geoms`, defaulting to 0.

**Comment by mjskay** [comment]
The fix-just branch now has a `position_dodgejust()` with some examples in `?position_dodgejust`. If you have a chance to try it out I'd appreciate it! I'd especially like to know if these changes address your needs here and in #86.

**Comment by mjskay** [comment]
Okay I think this is all fixed and documented now. Feel free to ping back around if there's something not working for it.
