### ISSUE TITLE
Specify point geom?

### ISSUE THREAD

**Issue by bwiernik** [mjskay/ggdist#86]
I'm wondering if it might be possible to allow the geom used for the point in the composite stats/geoms to be customized? Specifically, I'm interested in substituting a geom_label/geom_richtext in place of the default point (cf. https://github.com/mjskay/ggdist/issues/85).

**Comment by mjskay** [comment]
Interesting... I think probably if we can get #85 working that makes the most sense as a solution to this, as it will be more generic. My feeling about composite geoms is they are mostly useful as shortcuts; as soon as you want to start customizing individual pieces beyond simple customizations it's easier to just specify the two pieces as separate layers --- of course unless things don't line up, as you found :). 

If we can solve the justification problem, does that solve your issue here?

**Comment by bwiernik** [comment]
Yep. Just wanted to raise the question.

**Comment by mjskay** [comment]
Closed via #85 unless something else comes up :)
