### ISSUE TITLE
space between slab and interval

### ISSUE THREAD

**Issue by ASKurz** [mjskay/ggdist#93]
With some plots, particularly dots plots, it's nice to have a small space between the bottom of the distribution and the point interval. Here's my current method for doing so:

```{r}
library(tidyverse)
library(ggdist)

mtcars %>% 
  ggplot(aes(x = mpg, y = 0)) +
  stat_dots() +
  stat_pointinterval(position = position_nudge(y = -0.05))
```
<img width="893" alt="Screen Shot 2021-08-10 at 1 52 22 PM" src="https://user-images.githubusercontent.com/19917004/128918341-b96b7b68-6780-4130-b73f-92d582157e3b.png">

Is there a simpler way that doesn't involve separating what would have been a single `stat_dotsinterval()` line into one line for `stat_dots()` and a second line for `stat_pointinterval()`?

**Comment by mjskay** [comment]
In general this is the recommended approach --- once you start having stuff that targets different parts of a composite geom it's often easier to break them up. The composites are really meant as shortcuts for the two geoms used simultaneously, and I'm reluctant to add too many parameters targeting this that or the other sub-part since that is just duplicating the functionality you already get for free by breaking them up (with approximately equal code complexity but worse learnability since you have to learn new parameters).

That said, you can use a negative value of the justification parameter to achieve something similar, except that justification changes the position of the slab relative to the interval and not the interval relative to the slab:

```r
library(tidyverse)
library(ggdist)

mtcars %>% 
    ggplot(aes(x = mpg, y = 0)) +
    stat_dotsinterval(justification = -0.1)
```
![image](https://user-images.githubusercontent.com/6345019/128920244-e33b4403-5cda-469c-adae-5a327cfbf962.png)

This usage is not standard but is supported.

If you really wanted to you could apply a justification and a nudge to get back to something like what you have:

```r
library(tidyverse)
library(ggdist)

mtcars %>% 
    ggplot(aes(x = mpg, y = 0)) +
    stat_dotsinterval(justification = -1/9, position = position_nudge(y = -0.1))
```
![image](https://user-images.githubusercontent.com/6345019/128920686-90aaf654-8c5a-472d-9f73-0cc6be03dd03.png)

Note that the correct justification to exactly cancel out a nudge of `.1` is actually `-1/9` not `.1`; this is because the justification is calculated relative to the slab `scale`, which defaults to `.9` (so the derivation is `justification = -0.1/0.9`). This ensures that in a justification of `0` the bottom edge of the slab touches the interval and in a justification of `1` the top edge touches no matter the value of `scale`. This is part of why I don't really recommend using negative justifications in this way; it's easier and clearer to separate the geoms.

**Comment by ASKurz** [comment]
This is excellent. Thanks for the thorough answer, @mjskay!

**Comment by mjskay** [comment]
oh! one thing I forgot to mention is that because the pointinterval still has a width of 1 centered on the interval (since its default `side` is `"both"`), your original code does have some extra space at the bottom. You can get rid of that by setting `side = "top"` or `height = 0`:

```r
library(tidyverse)
library(ggdist)

mtcars %>% 
    ggplot(aes(x = mpg, y = 0)) +
    stat_dots() +
    stat_pointinterval(position = position_nudge(y = -0.05), side = "top")  # or height = 0
```
![image](https://user-images.githubusercontent.com/6345019/128935957-c02f095d-a1b2-426f-8bb5-e4f1947e9ac9.png)

**Comment by ASKurz** [comment]
I didn't know that! You know, I've been futzing with `coord_cartesian(ylim = c(blah, blah))` for like forever with that issue. The `height = 0` trick is a major upgrade, for me.

**Comment by mjskay** [comment]
Yeah I have mixed feelings about it because it's not very discoverable... it makes dodging easier for pointintervals to have a default width (e.g. it makes their positioning consistent with other geoms if you want to line up multiple layers), but makes plot limits annoying at times. I dunno, hard to change it now 🤷. Probably I should just add an example to a vignette somewhere.
