### ISSUE TITLE
Can position take a vector from position_nudge?

### ISSUE THREAD

**Issue by rcalinjageman** [mjskay/ggdist#99]
I'd like to nudge distributions over on a graph depending on a data column/vector (e.g. position = position_nudge(c = (0.5, 0.5, 0)).  When I try this with ggdist I get some odd behavior-- two copies of each distribution are produced, one un-nudged and one nudged, and only the first value of the vector seems to matter.  For other geoms, like geom_point, using a vector with position_nudge gives the expected behavior.

I have a code example below-- the goal is to nudge the first two distributions over to make space for raw data but to leave the third row, which has no raw data, un-nudged.  It may be that I need a completely different approach.  I've tried position = "dodge" with no luck.  I guess another approach would be to first plot the group distributions with a constant nudge and then plot the difference without a nudge... but open to any suggestions.

Here's example code:

`# Libraries
library(ggplot2)
library(ggdist)
library(distributional)

# Population params for desired data
population <- data.frame(
  condition = c("Group1", "Group2"),
  mu = c(100, 115),
  sigma = c(15, 15),
  n = c(50, 45)
)

# Simulate raw data and calculate summary data
raw_data <- NULL
summary_data <- NULL

for (i in 1:nrow(population)) {
  this_condition <- data.frame(
    condition = rep(population[i, "condition"], times = population[i, "n"]),
    outcome = rnorm(
      n = population[i, "n"], 
      mean = population[i, "mu"],
      sd = population[i, "sigma"]
    )
  )

  summary_data <- rbind(
    summary_data,
    data.frame(
      condition = c(population[i, "condition"]),
      mean = mean(this_condition$outcome),
      sd = sd(this_condition$outcome),
      se = sd(this_condition$outcome) / sqrt(nrow(this_condition)),
      n = nrow(this_condition),
      df = nrow(this_condition) - 1
    )
  )

  raw_data <- rbind(
    raw_data,
    this_condition
  )
}

# Difference between groups
diff_m <- summary_data[1, "mean"] - summary_data[2, "mean"]
diff_df <- sum(summary_data$df)
diff_se <- sqrt(sum(summary_data$sd^2 / summary_data$n))

summary_data[3, c("mean", "se", "df")] <- c(
  diff_m,
  diff_se,
  diff_df
)
summary_data[3, "condition"] <- "Difference"

summary_data$nudge <- c(0.3, 0.3, 0)

# Fix condition factor to ensure difference is plotted last
summary_data$condition <- factor(
  summary_data$condition, 
  levels = summary_data$condition
)
raw_data$condition <- factor(
  raw_data$condition,
  levels = summary_data$condition
)

# Now the plot
myplot <- ggplot2::ggplot(data = summary_data)

myplot <- myplot + ggdist::stat_dist_halfeye(
  data = summary_data,
  ggplot2::aes(
    x = condition, 
    y = mean,
    dist = distributional::dist_student_t(
      df = df, 
      mu = mean, 
      sigma = se
    )
  ),
  scale = 0.33,
  position = position_nudge(x = summary_data$nudge)
)

myplot <- myplot + ggplot2::geom_point(
  data = raw_data,
  aes(
    x = condition,
    y = outcome
  ),
  position = position_jitter(width = 0.2)
)

myplot
`

**Comment by mjskay** [comment]
Yeah, the problem is that `position_nudge` gets applied after the `stat`s are. What's happening internally is that `stat_dist_halfeye()` is producing a data frame that contains density values and the points and intervals and this is being passed to `position_nudge()` (and then eventually to the underlying geometry).

This data frame will be (by default) 501 x number of groups + 2 x number of groups in length --- 501 values from each density plus one row per interval per group. What's happening is that your vector of 3 values is being recycled to cover those (501 + 2) * 3 = 1509 rows, but not in a way that lines up with the rows corresponding to each group. Instead, if you give a vector of `c(0.3, 0.3, 0)`, the values are interleaved, so you would end up with 2/3s of the density values for each group having a nudge of `0.3` and 1/3 having a nudge of `0`, hence the apparent duplication.

One (**bad and not recommended**) solution would be to give a nudge vector of length 1509:

```r
myplot <- ggplot2::ggplot(data = summary_data)

myplot <- myplot + ggdist::stat_dist_halfeye(
    data = summary_data,
    ggplot2::aes(
        x = condition,
        y = mean,
        dist = distributional::dist_student_t(
            df = df,
            mu = mean,
            sigma = se
        )
    ),
    scale = 0.33,
    position = position_nudge(x = c(rep(summary_data$nudge, each = 501), rep(summary_data$nudge, each = 2)))
)

myplot <- myplot + ggplot2::geom_point(
    data = raw_data,
    aes(
        x = condition,
        y = outcome
    ),
    position = position_jitter(width = 0.2)
)

myplot
```
![image](https://user-images.githubusercontent.com/6345019/132744830-3c119336-5a01-4414-bbdc-483558892582.png)

This is a bad solution because it relies on the order of rows in the internal dataframe not changing in future implementations of ggdist, which I cannot guarantee. So, while it works, I would not recommend it.

Some alternatives: one would be to use two different geoms to specify the nudges seperately. You can avoid code duplication by using a temporary function to do it:

```r
myplot <- ggplot2::ggplot(data = summary_data)

make_halfeye <- function(...) {
  ggdist::stat_dist_halfeye(
    ggplot2::aes(
        x = condition,
        y = mean,
        dist = distributional::dist_student_t(
            df = df,
            mu = mean,
            sigma = se
        )
    ),
    scale = 0.33,
    ...
  )
}

myplot <- myplot + 
  make_halfeye(data = filter(summary_data, condition != "Difference"), position = position_nudge(x = 0.3)) +
  make_halfeye(data = filter(summary_data, condition == "Difference"))

myplot <- myplot + ggplot2::geom_point(
    data = raw_data,
    aes(
        x = condition,
        y = outcome
    ),
    position = position_jitter(width = 0.2)
)

myplot
```
![image](https://user-images.githubusercontent.com/6345019/132746048-2b9b6032-c167-4880-bc13-ccc80fb62581.png)

The axis order is different, but you could re-order that by adding `scale_x_discrete(limits = c("Group1", "Group2", "Difference"))` to the above.

A final option would be to apply the offsets directly to the x position values in the numeric space, by converting the factors to numeric first. This does require the use of `scale_x_discrete()`, otherwise you get an error:

```r
myplot <- ggplot2::ggplot(data = summary_data)

myplot <- myplot + ggdist::stat_dist_halfeye(
    data = summary_data,
    ggplot2::aes(
        x = as.numeric(condition) + nudge,
        y = mean,
        dist = distributional::dist_student_t(
            df = df,
            mu = mean,
            sigma = se
        )
    ),
    scale = 0.33
)

myplot <- myplot + ggplot2::geom_point(
    data = raw_data,
    aes(
        x = condition,
        y = outcome
    ),
    position = position_jitter(width = 0.2)
)

myplot + scale_x_discrete(limits = levels(summary_data$condition))
```
![image](https://user-images.githubusercontent.com/6345019/132746646-97fc7098-4340-40c5-b6e0-e9a680905745.png)


Hope that helps!

**Comment by rcalinjageman** [comment]
Wow.  Thanks.  This is incredibly helpful.  
Also, it finally dawned on me that I could nudge the raw data by a constant rather than the summary data by a varying value.  :-)
